    Queries Analysis 

-- 1) Retrieve all books in the "Fiction" genre:
SELECT * FROM Books
	WHERE Genre='Fiction';


-- 2) Find books published after the year 1950:
SELECT * FROM Books
WHERE Published_Year > 1950;

-- 3) List all customers from the Canada:
SELECT * FROM Customers
WHERE country ='Canada';


-- 4) Show orders placed in November 2023:
SELECT * FROM Orders
WHERE order_date BETWEEN '2023-11-01' AND '2023-11-30';
 
-- 5) Retrieve the total stock of books available:

SELECT SUM(stock) AS Total_Stock
From Books;


-- 6) Find the details of the most expensive book:
SELECT * FROM Books 
ORDER BY Price DESC 
LIMIT 1;


-- 7) Show all customers who ordered more than 1 quantity of a book:
SELECT * FROM Orders 
WHERE quantity>1;



-- 8) Retrieve all orders where the total amount exceeds $20:
SELECT * FROM Orders 
WHERE total_amount>20;



-- 9) List all genres available in the Books table:
SELECT DISTINCT genre FROM Books;


-- 10) Find the book with the lowest stock:
SELECT * FROM Books 
ORDER BY stock 
LIMIT 1;


-- 11) Calculate the total revenue generated from all orders:
SELECT SUM(total_amount) As Revenue 
FROM Orders;

-- Advance Questions : 

-- 12) Retrieve the total number of books sold for each genre:

SELECT * FROM ORDERS;

SELECT b.Genre, SUM(o.Quantity) AS Total_Books_sold
FROM Orders o
JOIN Books b ON o.book_id = b.book_id
GROUP BY b.Genre;


-- 13) Find the average price of books in the "Fantasy" genre:
SELECT AVG(price) AS Average_Price
FROM Books
WHERE Genre = 'Fantasy';


-- 14) List customers who have placed at least 2 orders:
SELECT o.customer_id, c.name, COUNT(o.Order_id) AS ORDER_COUNT
FROM orders o
JOIN customers c ON o.customer_id=c.customer_id
GROUP BY o.customer_id, c.name
HAVING COUNT(Order_id) >=2;




-- 15) Find the most frequently ordered book:
SELECT o.Book_id, b.title, COUNT(o.order_id) AS ORDER_COUNT
FROM orders o
JOIN books b ON o.book_id=b.book_id
GROUP BY o.book_id, b.title
ORDER BY ORDER_COUNT DESC LIMIT 1;



-- 16) Show the top 3 most expensive books of 'Fantasy' Genre :
SELECT * FROM books
WHERE genre ='Fantasy'
ORDER BY price DESC LIMIT 3;


-- 17) Retrieve the total quantity of books sold by each author:

SELECT b.author, SUM(o.quantity) AS Total_Books_Sold
FROM orders o
JOIN books b ON o.book_id=b.book_id
GROUP BY b.Author;





-- 18) List the cities where customers who spent over $30 are located:

SELECT DISTINCT c.city, o.total_amount
FROM orders o
JOIN customers c ON o.customer_id=c.customer_id
WHERE o.total_amount > 30;


-- 19) Find the customer who spent the most on orders:
SELECT c.customer_id, c.name, SUM(o.total_amount) AS Total_Spent
FROM orders o
JOIN customers c ON o.customer_id=c.customer_id
GROUP BY c.customer_id, c.name
ORDER BY Total_spent Desc LIMIT 1;


--20) Calculate the stock remaining after fulfilling all orders:

SELECT b.book_id, b.title, b.stock, COALESCE(SUM(o.quantity),0) AS Order_quantity,  
	b.stock- COALESCE(SUM(o.quantity),0) AS Remaining_Quantity
FROM books b
LEFT JOIN orders o ON b.book_id=o.book_id
GROUP BY b.book_id ORDER BY b.book_id;

-- 21) Find the top 5 customers by total spending:

SELECT c.customer_id, c.name, SUM(o.total_amount) AS Total_Spent
FROM Orders o
JOIN Customers c ON o.customer_id = c.customer_id
GROUP BY c.customer_id, c.name
ORDER BY Total_Spent DESC
LIMIT 5;



-- 22) Calculate revenue generated by each genre:

SELECT b.genre, SUM(o.total_amount) AS Total_Revenue
FROM Orders o
JOIN Books b ON o.book_id = b.book_id
GROUP BY b.genre
ORDER BY Total_Revenue DESC;



-- 23) Find the number of orders placed by each customer:

SELECT c.customer_id, c.name, COUNT(o.order_id) AS Total_Orders
FROM Customers c
JOIN Orders o ON c.customer_id = o.customer_id
GROUP BY c.customer_id, c.name
ORDER BY Total_Orders DESC;



-- 24) Retrieve the top 5 best-selling books:

SELECT b.book_id, b.title, SUM(o.quantity) AS Books_Sold
FROM Orders o
JOIN Books b ON o.book_id = b.book_id
GROUP BY b.book_id, b.title
ORDER BY Books_Sold DESC
LIMIT 5;



-- 25) Find authors whose books sold more than 10 copies:

SELECT b.author, SUM(o.quantity) AS Total_Copies_Sold
FROM Orders o
JOIN Books b ON o.book_id = b.book_id
GROUP BY b.author
HAVING SUM(o.quantity) > 10
ORDER BY Total_Copies_Sold DESC;



-- 26) Find the average order value:

SELECT ROUND(AVG(total_amount),2) AS Average_Order_Value
FROM Orders;



-- 27) Show the total revenue generated by each author:

SELECT b.author, SUM(o.total_amount) AS Revenue
FROM Orders o
JOIN Books b ON o.book_id = b.book_id
GROUP BY b.author
ORDER BY Revenue DESC;



-- 28) Find customers who never placed any order:

SELECT c.customer_id, c.name
FROM Customers c
LEFT JOIN Orders o ON c.customer_id = o.customer_id
WHERE o.order_id IS NULL;



-- 29) Find the most popular genre based on quantity sold:

SELECT b.genre, SUM(o.quantity) AS Total_Sold
FROM Orders o
JOIN Books b ON o.book_id = b.book_id
GROUP BY b.genre
ORDER BY Total_Sold DESC
LIMIT 1;



-- 30) Calculate the percentage contribution of each genre to total revenue:

SELECT b.genre,
       ROUND(SUM(o.total_amount) * 100.0 /
       (SELECT SUM(total_amount) FROM Orders),2) AS Revenue_Percentage
FROM Orders o
JOIN Books b ON o.book_id = b.book_id
GROUP BY b.genre
ORDER BY Revenue_Percentage DESC;


-- 31) Rank books based on total sales revenue:

SELECT b.book_id,
       b.title,
       SUM(o.total_amount) AS Revenue,
       RANK() OVER(ORDER BY SUM(o.total_amount) DESC) AS Revenue_Rank
FROM Orders o
JOIN Books b ON o.book_id = b.book_id
GROUP BY b.book_id, b.title;

-- 32) Find customers whose spending is above average:

WITH Customer_Spending AS (
    SELECT customer_id,
           SUM(total_amount) AS Total_Spent
    FROM Orders
    GROUP BY customer_id
)
SELECT *
FROM Customer_Spending
WHERE Total_Spent >
(
    SELECT AVG(Total_Spent)
    FROM Customer_Spending
);
